config/routes.rb
Rails.application.routes.draw do

  resources :likes, :only => [:create, :destroy]

  devise_for :users
  resources :employers

  get 'pages/about'

  get 'pages/contact'

  root 'employers#index'

end

app/models/employer.rb
class Employer < ActiveRecord::Base
	mount_uploader :image, ImageUploader
	has_many :likes
	has_many :users, through: :likes
end

app/models/like.rb
class Like < ActiveRecord::Base

	belongs_to :user
	belongs_to :employer
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  	devise :database_authenticatable, :registerable,
  	       :recoverable, :rememberable, :trackable, :validatable

	has_many :likes
	has_many :employers, through: :likes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/employers_controller.rb
class EmployersController < ApplicationController
  before_action :set_employer, only: [:show, :edit, :update, :destroy]

  # GET /employers
  # GET /employers.json
  def index
    @search = Employer.search(params[:q])


    @employers = @search.result
    
  end

  # GET /employers/1
  # GET /employers/1.json
  def show
  end

  # GET /employers/new
  def new
    @employer = Employer.new
  end

  # GET /employers/1/edit
  def edit
  end

  # POST /employers
  # POST /employers.json
  def create
    @employer = Employer.new(employer_params)

    respond_to do |format|
      if @employer.save
        format.html { redirect_to @employer, notice: 'Employer was successfully created.' }
        format.json { render :show, status: :created, location: @employer }
      else
        format.html { render :new }
        format.json { render json: @employer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employers/1
  # PATCH/PUT /employers/1.json
  def update
    respond_to do |format|
      if @employer.update(employer_params)
        format.html { redirect_to @employer, notice: 'Employer was successfully updated.' }
        format.json { render :show, status: :ok, location: @employer }
      else
        format.html { render :edit }
        format.json { render json: @employer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employers/1
  # DELETE /employers/1.json
  def destroy
    @employer.destroy
    respond_to do |format|
      format.html { redirect_to employers_url, notice: 'Employer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employer
      @employer = Employer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employer_params
      params.require(:employer).permit(:name, :address, :website, :industry, :size, :city, :state, :country, :evp, :status, :image)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
  	@like = Like.create(like_params)
    @employer = @like.employer
    render :toggle
  end

  def destroy
    like = Like.find(params[:id]).destroy
    @employer = like.employer
    render :toggle
  end


  private
    def like_params
      params.require(:like).permit(:user_id, :employer_id)
    end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employers_helper.rb
module EmployersHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/employers/_form.html.erb
<%= form_for(@employer, :html => { multipart: true }) do |f| %>
  <% if @employer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employer.errors.count, "error") %> prohibited this employer from being saved:</h2>

      <ul>
      <% @employer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :industry %><br>
    <%= f.text_field :industry %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <!-- <div class="field">
    <%= f.label :size %><br>
    <%= f.text_field :size %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :evp %><br>
    <%= f.text_field :evp %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div> -->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employers/edit.html.erb
<h1>Editing Employer</h1>

<%= render 'form' %>

<%= link_to 'Show', @employer %> |
<%= link_to 'Back', employers_path %>

app/views/employers/index.html.erb
<p id="notice"><%= notice %></p>

<% if user_signed_in? %>



<%= search_form_for @search do |f| %>

  <div class="field">
    <%= f.label :name_cont, "Name contains" %>
    <%= f.text_field :name_cont %>
  </div>
  <div class="actions"><%= f.submit "Search" %></div>

<% end %>
<% if !@search.conditions.empty? %>
  <table class="table table-hover table-condensed">
    <thead>
      <tr>
        <th>Name</th>
        <th>Address</th>
        <th>Website</th>
        <th>Industry</th>
  <!--       <th>Size</th>
        <th>City</th>
        <th>State</th>
        <th>Country</th>
        <th>Evp</th>
        <th>Status</th> -->
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @employers.each do |employer| %>
        <tr>
          <td><%= employer.name %></td>
          <td><%= employer.address %></td>
          <td><%= employer.website %></td>
          <td><%= employer.industry %></td>
  <!--         <td><%= employer.size %></td>
          <td><%= employer.city %></td>
          <td><%= employer.state %></td>
          <td><%= employer.country %></td>
          <td><%= employer.evp %></td>
          <td><%= employer.status %></td> -->
          <td><%= link_to 'Show', employer %></td>
          <td><%= link_to 'Edit', edit_employer_path(employer) %></td>
          <td><%= link_to 'Destroy', employer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <% end %>

<br>

<%= link_to 'Add New Employer', new_employer_path %>

<% else %>
<div class="intro">
  <h2>TalentPoolMe is the best way for undergraduates and employers to connect</h2>
  <h3>Explore potential companies, careers, and industries</h3>
  <%= link_to "Find Your Calling", new_user_registration_path, class: "btn btn-lg btn-primary", id: "signupbutton" %>
</div>
<% end%>

app/views/employers/new.html.erb
<h1>New Employer</h1>

<%= render 'form' %>

<%= link_to 'Back', employers_path %>

app/views/employers/show.html.erb
<p id="notice"><%= notice %></p>

<%= image_tag(@employer.image) %>

<p>
  <strong>Name:</strong>
  <%= @employer.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @employer.address %>
</p>

<p>
  <strong>Website:</strong>
  <%= link_to @employer.website, @employer.website %>
</p>

<p>
  <strong>Industry:</strong>
  <%= @employer.industry %>
</p>

<!-- <p>
  <strong>Size:</strong>
  <%= @employer.size %>
</p>

<p>
  <strong>City:</strong>
  <%= @employer.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @employer.state %>
</p>

<p>
  <strong>Country:</strong>
  <%= @employer.country %>
</p>

<p>
  <strong>Evp:</strong>
  <%= @employer.evp %>
</p>

<p>
  <strong>Status:</strong>
  <%= @employer.status %>
</p> -->
<div id="like">
  <%= render 'likes/like_button', :product => @product %>
</div>
<br>
<%= link_to 'Edit', edit_employer_path(@employer) %> |
<%= link_to 'Back', employers_path %>

app/views/layouts/_footer.html.erb
<footer>
	<div class="container-fluid">

		<div class="footer-links center">
			<ul>
				<li><%= link_to "User Agreement", "#" %> </li>
				<li><%= link_to "Privacy Policy", "#" %></li>
				<li><%= link_to "Community Guidelines", "#" %></li>
				<li><%= link_to "Cookie Policy", "#" %></li>
				<li><%= link_to "Copyright Policy", "#" %></li>
			</ul>
		</div>


	</div>
</footer>

app/views/layouts/_navbar.html.erb
<header>
	<nav class="navbar navbar-default" role="navigation">
	  <div class="container-fluid">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <%= link_to image_tag("TalentLogo.png"), root_path%>
	    </div>

	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav navbar-right">
	        <li><%= link_to 'About', pages_about_path %></li>
	        <li><%= link_to 'Contact', pages_contact_path %></li>
	        <% if user_signed_in? %>
	        <li class="dropdown">
	          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">My Account <span class="caret"></span></a>
	          <ul class="dropdown-menu" role="menu">
	            <li><%= link_to "My Profile", edit_user_registration_path %></li>

	            <li class="divider"></li>
	            <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>

	          </ul>
	        </li>
	        <% else %>
	        <li><%= link_to "Sign in", new_user_session_path %></li>
	        <% end %>
	      </ul>
	        

	      
	      
	    </div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->
	</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TalentPoolMeDraft</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<%= render 'layouts/navbar' %>


	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>

	<%= yield %>

	</div>

	<%= debug(params) if Rails.env.development? %>
	<%= render 'layouts/footer' %>

</body>
</html>

app/views/likes/_like_button.html.erb
<% current_user = User.first %>

<% if like = current_user.likes.where(employer_id: @employer.id).first %>
	<%= form_for like, :html => { :method => :delete }, :remote => true do |f| %>
		<%= f.submit "Unlike" %>
	<% end %>
<% else %>
	<%= form_for current_user.likes.build(:employer_id => @employer.id), :remote => true do |f| %>
		<%= f.hidden_field :employer_id %>
		<%= f.hidden_field :user_id %>
		<%= f.submit "Like" %>
	<% end %>
<% end %>

app/views/likes/toggle.js.erb
$("#like").html("<%= escape_javascript render('like_button') %>");

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>